- name: —Åreate directory
  file:
    path={{root_dir}}
    state=directory
  become: yes
  tags: [system, nginx]

- name : Insatll nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  become: yes
  tags: nginx

- name: Install cowsay
  ansible.builtin.apt:
    name: cowsay
    state: present
  become: yes
  tags: nginx
  
- ansible.builtin.shell: cowsay "This is server server_name!"
  register: result
  tags: nginx

- name: update index
  ansible.builtin.template:
    src: ../app/index.html
    dest: "{{root_dir}}/index.html" 
  become: yes
  tags: nginx

- name: update nginx config
  ansible.builtin.template:
    src: ../configs/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  become: yes
  tags: nginx
