- hosts: servers
  # gather_facts: no
  vars:
    users: 
      - { name: jaime, groups: user }
      - { name: sansa, groups: user }
      - { name: robert, groups: user }
  tasks:
    - name: Update cahe Ubuntu
      ansible.builtin.command: apt update
      when: ansible_os_family == "Debian"
      become: yes
      tags: system

    - name: Update cache Centos
      ansible.builtin.command: yum update
      when: ansible_os_family == "RedHat"
      become: yes
      tags: system

    - name: Install git Centos
      ansible.builtin.yum:
        name: git
        state: present
      when: ansible_os_family == "RedHat"
      become: yes
      tags: git

    - name: Install git Ubuntu
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      become: yes
      tags: git

    - name: Create group user
      ansible.builtin.group:
        name: user
        state: present
      become: yes
      tags: group

    - name: Create users
      ansible.builtin.user:
        name: "{{item.name}}"
        state: present
        groups: "{{item.groups}}"
      loop: "{{users}}"
      become: yes
      tags: user

    - name: Update git config
      ansible.builtin.template:
        src: ../files/.gitconfig
        dest: "/home/{{item.name}}/.gitconfig"
        group: "{{item.name}}"
        owner: "{{item.name}}"
      loop: "{{users}}"
      become: yes
      tags: system

    - name: Create .shh dir
      ansible.builtin.file:
        path: "/home/{{item.name}}/.ssh/authorized_keys"
        state: directory
        recurse: yes
        owner: "{{item.name}}"
        group: "{{item.name}}"
        mode: '0600'
      loop: "{{users}}"
      become: yes

    - name: Copy ssh key
      ansible.builtin.copy:
        src: "../files/{{item.name}}/id_ed25519.pub"
        dest: "/home/{{item.name}}/.ssh/authorized_keys"
        owner: "{{item.name}}"
        group: "{{item.name}}"
      loop: "{{users}}"
      become: yes
      tags: system

