---
- hosts: localhost
  gather_facts: no
  tasks:
    - template:
        src: ../files/terraform/secrets.tfvars.j2
        dest: ../secrets.tfvars

    - name: Get ssh key
      ansible.builtin.shell: cat /home/$USER/.ssh/id_rsa.pub
      register: ssh_key
    
    - name: Get user name
      ansible.builtin.shell: echo $USER
      register: user

    - template:
        src: ../files/terraform/meta.txt.j2
        dest: ../meta.txt

