---
- name: Update cahe Ubuntu
  ansible.builtin.command: apt update
  become: yes
  tags: system

- name : Insatll nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  become: yes
  tags: nginx

- name: Install cowsay
  ansible.builtin.apt:
    name: cowsay
    state: present
  become: yes
  tags: nginx
  
- ansible.builtin.shell: cowsay "This is server server_name!"
  register: result
  tags: nginx


